### ISSUE TITLE
ScriptHookVDotNet Nightly versions not compatible with .vb scripts?

### ISSUE THREAD

**Issue by JAM102970** [kagikn/kagikn#1]
Does anybody knows how to get .vb scripts to work with SHVDN Nightly versions?  I know by adding .2 to .cs scripts works with the nightly versions but, I can't get .vb scripts to work with it.  If I install a .vb script into my gta 5 game it just crashes the game right off.

**Comment by kagikn** [comment]
Please go to [Discussions on the ScriptHookVDotNet organization](https://github.com/scripthookvdotnet/scripthookvdotnet/discussions/new/choose) and ask the same question there, but with a example that explains what .vb script crashes your game. I'm not answering your question in here.
